#!/bin/bash
# You can use this to get a VCD
# You will need to compile la2vcd, of course
# and set your serial port, etc.
../../../c/la2vcd -F 48 -b 9600 -t 129 -c 2 -r 1 -n 256 -o demo2.vcd /dev/ttyUSB1
