#!/bin/bash
# You can use this to get a VCD
# You will need to compile la2vcd, of course
# and set your serial port, etc.
../../../c/la2vcd -F 12 -b 9600 -t 513 -c 2 -r 2 -n 1024 -o spin.vcd /dev/ttyUSB1
